version: 2.1

jobs:
  build:
    docker:
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python --version
            python3.7 -m venv venv
            . venv/bin/activate
            pip install pylint
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
  docker-build-push:
    docker:
      # - image: circleci/python:3.7.3
    machine: true
    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSOWRD}
            make buildpushblue
            make buildpushgreen

workflows:
  default:
    jobs:
      - build
      - docker-build-push:
          requires: [build]

